scalar JSON

type Query {
  client(username: String, key: String): Client
  user: User

  game(name: String!): Game

  store(handle: String!): Store
  stores: JSON

  product(id: ID!): Product
  products(handle: String!): [Product!]!

  institutions: [Institution!]!
  places: [Place!]!
}
