scalar JSON

type Store {
  id: ID!
  name: String!
  handle: String!
  type: String!
  img: String!
  bio: String!
  creator: ID!
}

type TGUError {
  code: String!
  message: String!
}

input CreateStoreInput {
  name: String!
  handle: String!
  type: String!
  bio: String!
}

type Mutation {
  createStore(input: CreateStoreInput!): Store!
}
